export const monacoEditorOption = {
    selectOnLineNumbers: true,
    autoIndent: true,
    smoothScrolling: true,
    snippetSuggestions: 'top',
    automaticLayout: true,
    autoClosingBrackets: true,
    acceptSuggestionOnEnter: 'on',
    colorDecorators: true,
    dragAndDrop: true,
    formatOnPaste: true,
    formatOnType: true,
    fontSize: 14,
    mouseWheelZoom: true,
}
